CREATE TABLE IF NOT EXISTS promo_cards (
    id SERIAL PRIMARY KEY,
    image_url TEXT NOT NULL,
    link_url TEXT NOT NULL,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
